# Generated by Django 3.1.7 on 2021-04-17 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos_label', '0002_auto_20210417_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='start_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
