# Generated by Django 3.1.7 on 2021-04-17 21:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos_label', '0003_auto_20210417_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='count',
            new_name='product_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_choice',
            field=models.IntegerField(blank=True, choices=[('10', 'PROMO 10'), ('15', 'PROMO 15'), ('25', 'FAVORITE CLIENT'), ('50', 'PERSONAL')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_label.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
