# Generated by Django 3.1.7 on 2021-04-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_label', '0005_auto_20210418_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_choice',
            field=models.IntegerField(blank=True, choices=[(10, 10), (15, 15), (25, 25), (50, 50)], default=None, max_length=2, null=True),
        ),
    ]
